language: node_js
node_js:
    - "lts/*"
cache:
    yarn: true
    directories:
        - "node_modules"
services:
    - mongodb
before_script:
    - mongo --eval 'db.hostInfo()'
script: yarn test
notifications:
    slack: hirsute:3M3jmE7DfB3N5qGuvzJ0SRI8