version: "3"

services:
    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - ./docker/mongo/data:/data/db
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - "8017:8081"
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
        depends_on:
            - mongo
        links:
            - mongo:mongo
    api:
        image: node:lts
        user: "node"
        working_dir: /home/node/app
        command: sh -c "yarn && DEBUG=api* yarn start-dev"
        ports:
            - 3000:3000
            - 4000:4000
            - 9009:9009
        environment:
            - NODE_ENV=development
            - MONGO_URI=${MONGO_URI}
            - MONGO_URI_TEST=${MONGO_URI_TEST}
        volumes:
            - ./:/home/node/app
        depends_on:
            - mongo
        links:
            - mongo:mongo
